- hosts: xen_nodes
  vars:
    home_dir: "{{ lookup('env','HOME') }}"
  sudo: True

  tasks:
    - name: Update apt repositories
      action: apt update_cache=True

    - name: Install dependencies
      action: apt pkg={{ item }} state=present
      with_items:
        - build-essential
        - texinfo
        - libpixman-1-dev
        - bridge-utils
        - git

    - name: Disable dhcp on em1 interface.
      shell: sudo sed -i 's/iface em1 inet dhcp/iface em1 inet manual/' /etc/network/interfaces

    - name: Configure Xen bridge with dhcp.
      shell: echo 'auto virbr0\n iface virbr0 inet dhcp\nbridge_ports em1' | sudo tee -a /etc/network/interfaces

    - name: Build dependencies for Xen
      action: command apt-get -y build-dep xen

    - git: repo=https://github.com/mdlugajczyk/xen.git dest={{ home_dir }}/xen-src version=round-robin

    - name: Configure
      shell: cd {{ home_dir }}/xen-src && ./configure --libdir=/usr/lib

    - name: Make
      command: chdir={{ home_dir }}/xen-src make dist

    - name: Make install
      command: chdir={{ home_dir }}/xen-src make install

    - name: Update rc scripts xencommons
      command: update-rc.d xencommons defaults 19 18

    - name: Update rc scripts xendomains
      command: update-rc.d xendomains defaults 21 20

    - name: Update rc scripts xen-watchdog
      command: update-rc.d xen-watchdog defaults 22 23

    - name: Select xen as first boot option in Grub
      shell: dpkg-divert --divert /etc/grub.d/08_linux_xen --rename /etc/grub.d/20_linux_xen

    - name: Update grub
      command: update-grub
